### ISSUE TITLE
Remove the caching as long as we are not using it.

### ISSUE THREAD

**Issue by drewstone** [edgeware-builders/anon#55]

**Comment by filiplazovic** [comment]
We will need a simpler form of caching where we save the latest root hash every few blocks, just so the clients can create proof against it and submit it before it changes.

**Comment by filiplazovic** [comment]
The solution mentioned above will still leave some failing transactions so, in order to provide a smooth experience, a simpler solution can be like:

Just have a linked list of the last `n` root hashes, keep track of the head and the tail in the list. Every `t` blocks remove the tail root hash and insert the current one (taken from storage) to the head of the list. This linked list can be implemented with BTreeMap

**Comment by drewstone** [comment]
So the feeling I'm getting is that we shouldn't touch the cache at all. It is sufficient for the use case atm and is efficiently implemented in the module's storage.
